=== dawmendoza2009/TareaXSD/xsd.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="tienda">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="productos">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="producto"  minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="clientes">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="cliente"  minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>

		</xs:complexType>
	</xs:element>

	<xs:element name="producto">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombreproducto" type="xs:string" />
				<xs:element name="categoria" type="xs:string" />			
				<xs:element name="precio" type="xs:decimal" />
				<xs:element name="fecha" type="xs:date" />
				<xs:element name="descripcion" type="xs:string" />
			</xs:sequence>
			<!--definición de atributos-->
			<xs:attribute name="codigo" type="codigopatron"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="cliente">
		<xs:complexType>
			<xs:all>
				<!--En lugar de secuencia all ya que en este caso nos dará igual el orden de los elementos-->
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="apellido" type="xs:string" />
				<!--Se declara la restrinccion fuera-->
				<xs:element name="mail" type="r-mail" />
				<xs:element name="dni" type="r-dni" />
				<xs:element name="provincia" type="xs:string" />				
				<xs:element name="codigopostal" type="xs:integer" />
				<xs:element name="fechanacimiento" type="xs:date" />
				<xs:element name="edad" type="xs:integer" />
				<xs:element name="telefono" type="r-telefono"/>
			</xs:all>
			<!--definición de atributos-->
			<xs:attribute name="codigo" type="codigopatron"/>
		</xs:complexType>
	</xs:element>

	<!--RESTRINCIONES:-->
	<!-- restrinción para el código de producto y cliente-->
	<xs:simpleType name="codigopatron">
		<xs:restriction base="xs:string">
			<!--el patrón se compone de 3 letras de la A a la Z mayúsculas, guión, 2 letras, guión y 4 números-->
			<xs:pattern value="[A-Z]{3}-[A-Z]{2}-[0-9]{4}"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- restrinción mail para que tenga formato mail-->
	<xs:simpleType name="r-mail">
		<xs:restriction base="xs:string">
			<!--el patrón se compone de varias letras de la A a la Z, un @, varias letras, un punto y 3 letrasde la A a la Z números-->
			<xs:pattern value="([a-z0-9])*@([a-z])*.([a-z]){3}" />
		</xs:restriction>
	</xs:simpleType>
	
	<!--restrinción longitud del telefono 9-->
	<xs:simpleType name="r-telefono">
		<xs:restriction
		base="xs:string">
			<!--<xs:length value="9" />-->
			<xs:pattern value="\(\+[0-9]{3}\)[0-9]{9}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!--restrinción DNI el dni tendrá 8 numeros y 1 letra mayuscula-->
	<xs:simpleType name="r-dni">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{8}[A-Z]{1}" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dawmendoza2009/TareaXSD/xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo.xsl"?>
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">

	<!--schemaLocation: archivo externo donde está el xsd-->
	<productos>
		<producto codigo="VID-ES-0012">
			<nombreproducto>Minecraft</nombreproducto>
			<categoria>Video juego</categoria>
			<precio>40</precio>
			<fecha>2022-12-05</fecha>
			<descripcion>
				Minecraft es un videojuego de mundo abierto donde la exploración y las construcciones son fundamentales.
			</descripcion>
		</producto>
		<producto codigo="MUS-FR-0077">
			<nombreproducto>Shakira</nombreproducto>
			<categoria>Música</categoria>
			<precio>100</precio>
			<fecha>2020-03-10</fecha>
			<descripcion>
				Nueva versión del disco de Shakira.
			</descripcion>
		</producto>
	</productos>
	<clientes>
		<cliente codigo="CLI-ES-0154">
			<nombre>Daniela</nombre>
			<apellido>Moreno</apellido>
			<apellido2>Fernandez</apellido2>
			<dni>75346667L</dni>
			<mail>danielamoreno57@gmail.com</mail>
			<provincia>Madrid</provincia>
			<codigopostal>28026</codigopostal>
			<edad>28</edad>
			<sexo>Mujer</sexo>
			<tipocliente>
				<clienteantiguo>Desde 1900</clienteantiguo>
			</tipocliente>
			<telefono>(+034)617867854</telefono>
		</cliente>
		<cliente codigo="CLI-ES-0155">
			<nombre>Jose Luis</nombre>
			<apellido>Pomacusi</apellido>
			<dni>88346667H</dni>
			<mail>pablo157@gmail.com</mail>
			<provincia>Barcelona</provincia>
			<codigopostal>28017</codigopostal>
			<tipocliente>
				<clientenuevo>Desde 2022</clientenuevo>			
			</tipocliente>
			<edad>28</edad>
			<sexo>Mujer</sexo>
			<telefono>(+034)617867854</telefono>
		</cliente>
		<cliente codigo="CLI-ES-0156">
			<nombre>Tatiana</nombre>
			<apellido>Gutierrez</apellido>
			<dni>55346667K</dni>
			<mail>pablo157@gmail.com</mail>
			<provincia>Madrid</provincia>
			<codigopostal>28017</codigopostal>
			<edad>28</edad>			
			<telefono>(+034)617867854</telefono>
		</cliente>

	</clientes>
</tienda>
